# -*- coding: utf-8 -*-
"""PRODIGY_GA_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qo6B07cXHIqYMHrL-JStfEidOP2DH-2n
"""

!pip install diffusers transformers accelerate scipy safetensors

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16
).to("cuda")

prompt = "a futuristic city floating in the clouds, digital art"
image = pipe(prompt).images[0]

# Show the image
plt.imshow(image)
plt.axis("off")
plt.show()

